name: HACS Validation

on:
  push:
    paths:
      - "custom_components/task_timers/**"
  pull_request:
    paths:
      - "custom_components/task_timers/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
          path: custom_components/task_timers
